spring:
  datasource:
    url: jdbc:oracle:thin:@//10.220.6.74:1521/ORCLPDB  # 改成你虚拟机的IP
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8080



# 旧的（beta版写法）
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${DASHSCOPE_API_KEY}
        model-name: qwen-max