name: CI

# 触发条件：push 代码、修改文件、提交 README 都会自动跑 CI
on:
  push:
    branches: [ main ]  # 你只有 main 分支
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile with Maven
        run: mvn compile
